export const CART_ADDITEM = 'CART/ADD_ITEM'
export const CART_REMOVEITEM = 'CART/REMOVE_ITEM'
export const CART_INCREASECOUNT = 'CART/INCREASE_COUNT'
export const CART_DECREASECOUNT = 'CART/DECREASE_COUNT'
